# Site
repOSitory: Git repOSitory where your resume will be hOSted, only required if you are hOSting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 서재현
title: Application Developer
email: martindec16@gmail.com
# email_title: Email (Email title override)
#phone: Your phone number (optional)
phone_title: 010-2588-4575
website: https://suhjaehyeon.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  "SuhJaeHyeon"
#instagram_username: "__martin1216"
#linkedin_username: ""

# Additional icon links
additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/sample1.jpg
about_content: | # this will include new lines to allow paragraphs
  Flutter 기반의 어플리케이션 개발자 서재현이라고 합니다.
  -	함께 일하는 것을 좋아합니다.
  -	소통하고 유기적인 문화 속에서 효율적인 성장과 공유를 추구합니다.
  -	사용자 친화적인 제품이 무엇일까에 대한 관심이 많습니다.
  -	단순한 것을 좋아합니다. 깔끔하고, 분명한 코드를 만들기 위해 고민합니다.

  <mark>Objective-c</mark>  <mark>swift</mark>  <mark>dart</mark>  <mark>(python, c++)</mark>  
    
content:
  - title: Career
    layout: list
    content:
      - layout: left
        title: 새하컴즈
        sub_title: Client Developer
        caption: 2020.07 ~ 2024.05
        quote: >
          화상회의 클라이언트 개발
        description: |
          - 화상회의 클라이언트(BODA) 개발(FLUTTER)
          - 화상회의 클라이언트(BODA) 개발 및 유지보수(IOS / MAC)
          - 화상채팅 앱(Argo) IOS 유지보수
          - 필기인식 AI 모듈 개발

  - title: Projects
    layout: list
    content:
    # Projects 1
      - layout: left
        title: Flutter를 활용한 앱 리뉴얼
        caption: 2023.01 ~ 2024.4
        quote: >
          Flutter를 활용한 앱 리뉴얼
        description: | 
          - 도입 전
              - 사내 Window, AOS, IOS & MacOS 개발자 총 3명이 클라이언트 개발
              - 개발 간 OS 별 로직에 차이가 생기고 그에 따른 오류 발생
          - 도입 후
              - Window, AOS, IOS, MacOS, Web 모든 환경에서 서비스 개발 
              - 모바일 개발자가 유동적으로 UI 개발을 진행함으로서 개발 소요가 줄어듦
              - OS 별 비지니스 로직이 같아 개발자 간 소통 및 이해가 용이
              - 전체적인 오류가 줄어들고, 유지보수 소요 감소
          - 도입 과정
              - 사내 SDK 개발 참여
              - UI 및 비지니스 로직 개발
              - MacOS & IOS 위주의 네이티브 소스 개발
              - IOS 앱 운영관리

    # Projects 2
      - layout: left
        title: 화상회의 솔루션 UI 옵션화
        caption: 2021.03 ~ 2024.4
        quote: >
          B2B 서비스 사업에서의 UI 옵션화를 통한 간결한 요구사항 적용
        description: | 
          - 도입 전
              - 수많은 고객사들의 UI Customizing의 수요 증가
              - 소스의 양이 늘고 BundleID에 따른 하드코딩 수준의 소스 증가
          - 도입 후
              - 새로운 고객사의 요구사항에 대한 유동적인 대응으로 빠른 앱 배포
              - 새로운 UI개발에 있어서 유기적인 코드 작성
              - 복잡한 UI 옵션에 비한 깔끔하고 코드 유지
          - 도입 과정
              - 회의실의 템플릿을 설정하여 Web에서 Rest통신으로 앱에게 string 송신
              - Enum 값으로 정리된 값에 따라 파싱 후 다수의 옵션화를 원활히 진행

    # Projects 3
      - layout: left
        title: 화면 공유 / 녹화 기능 개발
        caption: 2021.10 ~ 2021.11
        quote: >
          IOS의 Extension(Replay Kit)을 기능 활용한 녹화 기능
        description: | 
          - 도입 이유
              - Zoom과 비교하여 화면공유 부재에 대한 고객사의 요구
              - 캡쳐 후 저장(녹화) 및 공유 기능 개발 수요 증가
          - 도입 과정
              - IOS의 Extension을 생성하여 GroupID 메모리에 접근
              - 사작, 종료, 영상, 음성에 대한 파일을 쓰기/읽기를 통한 정보 공유

    # Projects 4
      - layout: left
        title: 보안모듈 연동작업
        caption: 2021.03 ~ 2024.4
        quote: >
          타사 MDM, VPN 등의 보안모듈 연동작업
        description: | 
          - 은행 및 공기업의 특성상 MDM, VPN 등의 보안업체와 연동하는 작업 다수 진행
            - 업체에서 제공하는 샘플과 메뉴얼을 통하여 연동작업
            - 문서를 통하여 유기적인 업무를 진행


    # Projects 5
      - layout: left
        title: 스티커, 가면 기능 도입
        caption: 2022.03 ~ 2022.04
        quote: >
          서비스 앱에 외부 머신러닝 모듈 적용
        description: | 
          - 도입 전
              - 화상채팅에서의 색상필터를 적용하는 기능밖에 없었음
          - 도입 후
              - 사용자들이 3D 가면 기능을 통해 더 풍부한 사용자 경험 구현
          - 도입 과정
              - Apple의 AppleKit, Metal, Google의 MLKit 연구 비교를 통해 얼굴 tracking을 통한 가면 기능 개발


    # Projects 6
      - layout: left
        title: 필기인식 AI 모듈 개발
        caption: 2023.04 ~ 2023.11
        quote: >
          숫자, 기호, 분수, 영문에 대한 필기 인식 모듈 개발 팀 리딩
        description: | 
          - 95% 수준의 모듈 개발
          - GNN, YOLO를 활용한 필기 인식 성능개선
          - 데이터 생성 프로그램 개발
          - Flutter를 활용한 테스트 앱 개발
          - 데이터 분석 및 개선사항 도출
          - 관련 눈문 작성



  - title: Experience
    layout: list
    content:
    # Experience 1
      - layout: left
        title: 공통 SDK 인터페이스 설계
        # sub_title: Job title
        # caption: Date Range (eg. November 2016 - present)
        quote: >
          공통 SDK 인터페이스 설계
        description: | # this will include new lines to allow paragraphs
          - Flutter 앱 리뉴얼 당시 아키텍쳐 구성
            - 사내 SDK 구성
              - BODA_APP
                - BODA_FLUTTER_SDK
                - BODA_LIB(이하 c++)
                  - BODA_API
                  - BODA_BASE
                  - BODA_UTIL
          - 새로운 프로젝트와 유기적인 연결, 코드관리 가능
          - 역할 분기와 데이터, 비지니스로직, UI와의 분리

    # Experience 2
      - layout: left
        title: 사용자 경험 향상을 위한 UI/UX 개선
        quote: >
          다양한 관점에서 UI/UX 개선 경험
        description: |
          - 쓰레드 관리를 통한 UI 개선
              - 비동기/동기 작업에 대한 정리
              - 코드정리를 통해 불필요한 delay 해결
          - 메모리 관리를 통한 UI 개선
              - AutoRelease 와 캐싱 등을 이용하여 빠르고 가벼운 UX 제공
          - API를 통해 비즈니스 로직 구현을 위한 사용자 인터페이스 구성 통한 UI 개선
            - UI를 옵션화하는 템플릿 설정을 웹에서 사전에 설정
            - 앱이 실행될때, 해당 내용을 bit 및 기타 프로토콜을 통하여 인터페이스 구현
          - 동기화 관리를 통한 UI 개선
            - 화면 전환, 영상처리, 필기&미디어 등의 동기화를 구분하고 프로토콜 정의
          - 버튼에 대한 공통 UX 정리 및 구현
              - 기존에는 버튼에 대한 효과가 즉흥적으로 개발 되어왔음
              - normal, press, hover, disable, toggle 등의 다양한 생상/효과 통일

    # Experience 3
      - layout: left
        title: IOS / MAC 앱 운영
        quote: >
          애플 스토어 앱 출시 및 Firebase 활용을 통한 앱 관리 
        description: | # this will include new lines to allow paragraphs
          - 스토어 앱 & 엔터프라이즈 앱 관리
              - 30개 이상의 고객사 앱 BundleID 및 인증서 관리
              - TestFlight 및 버전 관리
          - FireBase를 통한 앱 관리
              - 사내 서비스 앱 Crashlytics 및 통계 수치를 통한 앱 유지관리

    # Experience 4
      - layout: left
        title: 새로운 환경에서의 적응
        quote: >
          갑작스런 IOS 개발자로서의 적응
        description: | # this will include new lines to allow paragraphs
          - 1 년차 window 개발자로서 IOS 개발자의 퇴사로 3주의 인수인계 후 IOS를 담당하게 됨
              - 초기 모르는 XCode 설정에 대해 선임자의 집 앞까지 찾아가서라도 해결결험
              - HIG, 블로그, 테스트 앱 등을 통해 지식 및 기술 습득
              - 이후 약 4년 간 IOS를 담당하여 원활히 운영
          - Memory Leak 해결
              - 코드 한줄 한줄 로그와 디버긴을 통해 메모리릭 해결
              - Profiling 기능을 통하여 메모리 릭 해결


    # Experience 5
      - layout: left
        title: 개발 문화 개선
        #sub_title: Job title
        #caption: Date Range (eg. November 2016 - present)
        #link: Link to company (optional)
        quote: >
          개발자가 성장 할 수 있는 개발 문화 도입
        description: | # this will include new lines to allow paragraphs
          - 각자 미루고 있던 개발 분야에 대한 개인 공부를 공유하는 스터디 진행
              -  매주 점심시간을 활용하여 20간 티타임시 돌아가며 발표
              - 네트워크, AI, 하드웨어, 등 주제를 가리지 않고 자신의 관심 있는 분야에 대해 공부

          - 팀 초기 2023 AI 박람회 참가 건의
              - AI에 대한 관점이 서로 다르던 초기 팀 구성 시 비전을 정하는데 큰 도움이 되었음

          - 테스트 앱 작성 및 공유


  - title: Education
    layout: list
    content:
      - layout: top-left
        title: 고려대학교
        sub_title: 정보통신대학원 인공지능융합학과
        caption: 2020.9 - 2024.2
        description: |
          - 석사 졸업
          - 논문 작성 : "GNN 기반의 온라인 필기 데이터로 이루어진 수식 인식에 관한 연구"

      - layout: top-left
        title: KG 평생교육원
        sub_title: 컴퓨터 공학
        caption: 2019.3 - 2020.2
        description: |
          - 학사 졸업
          - 개발을 공부하기 위해 군 생활과 병행하여 복수전공 졸업

      - layout: top-left
        title: 연세대학교
        sub_title: 이과대학 대기과학과
        caption: 2014.3 - 2018.2
        description: |
          - 학사 졸업
          - 수학, 물리, 모델링 등에 관련된 학업 학습


  - title: A Little More About Me
    layout: text
    content: |
      자격증
      -	정보 처리 기사(2021. 03 취득)
      -	토스 Intermediate High (Speaking Score 150)

      군 경력
      -	2018.02 ~ 2020.06	중위 전역 / ROTC

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hOSting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hOSting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compOSe.yml",
  ]
